# Generated by Django 4.2.3 on 2023-07-06 02:56

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=50, verbose_name='Brand Name')),
                ('mname', models.CharField(max_length=100, verbose_name='Model Name')),
                ('price', models.FloatField(verbose_name='Orignal Price')),
                ('oprice', models.FloatField(verbose_name='Offer Price')),
                ('offer', models.FloatField(verbose_name='offer discount')),
                ('cat', models.IntegerField(choices=[(5, 'Lenovo'), (3, 'Dell'), (1, 'Acer'), (4, 'HP'), (2, 'Asus')], verbose_name='Brand Name')),
                ('ss', models.IntegerField(verbose_name='Screen Size')),
                ('hds', models.IntegerField(verbose_name='Hard Disk Size')),
                ('rms', models.IntegerField(verbose_name='Ram Memory Installed Size')),
                ('os', models.CharField(max_length=100, verbose_name='Operating System')),
                ('is_active', models.BooleanField(default=True)),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=50)),
                ('qty', models.IntegerField(default=1)),
                ('amt', models.FloatField(default=0)),
                ('date', models.DateTimeField(verbose_name='Order Date')),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='shopeeapp.index')),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Userdb',
            fields=[
                ('userid', models.OneToOneField(db_column='userid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fname', models.CharField(max_length=100, verbose_name='First Name')),
                ('lname', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(db_column='email', max_length=254, verbose_name=django.contrib.auth.models.User)),
                ('gender', models.CharField(max_length=20)),
                ('city', models.CharField(choices=[('Akola', 'Akola'), ('Amravati', 'Amravati'), ('Aurangabad', 'Aurangabad'), ('Bhandara', 'Bhandara'), ('Buldhana', 'Buldhana'), ('Chandrapur', 'Chandrapur'), ('Dhule', 'Dhule'), ('Gadchiroli', 'Gadchiroli'), ('Gondia', 'Gondia'), ('Hingoli', 'Hingoli'), ('Jalna', 'Jalna'), ('Nagpur', 'Nagpur'), ('Nanded', 'Nanded'), ('Nashik', 'Nashik'), ('Osmanabad', 'Osmanabad'), ('Parbhani', 'Parbhani'), ('Ratnagiri', 'Ratnagiri'), ('Sangli', 'Sangli'), ('Satara', 'Satara'), ('Sindhudurg', 'Sindhudurg'), ('Solapur', 'Solapur'), ('Thane', 'Thane'), ('Wardha', 'Wardha'), ('Washim', 'Washim')], max_length=100)),
                ('pincode', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orderhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=50)),
                ('qty', models.IntegerField(default=1)),
                ('amt', models.FloatField(default=0)),
                ('date', models.ForeignKey(db_column='date', on_delete=django.db.models.deletion.CASCADE, to='shopeeapp.order')),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='shopeeapp.index')),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='shopeeapp.index')),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
