# Generated by Django 4.2.3 on 2023-07-15 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopeeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=100, verbose_name='First Name')),
                ('ln', models.CharField(max_length=100, verbose_name='Last Name')),
                ('mobno', models.CharField(max_length=90)),
                ('city', models.CharField(choices=[('Akola', 'Akola'), ('Amravati', 'Amravati'), ('Aurangabad', 'Aurangabad'), ('Bhandara', 'Bhandara'), ('Buldhana', 'Buldhana'), ('Chandrapur', 'Chandrapur'), ('Dhule', 'Dhule'), ('Gadchiroli', 'Gadchiroli'), ('Gondia', 'Gondia'), ('Hingoli', 'Hingoli'), ('Jalna', 'Jalna'), ('Nagpur', 'Nagpur'), ('Nanded', 'Nanded'), ('Nashik', 'Nashik'), ('Osmanabad', 'Osmanabad'), ('Pune', 'Pune'), ('Parbhani', 'Parbhani'), ('Ratnagiri', 'Ratnagiri'), ('Sangli', 'Sangli'), ('Satara', 'Satara'), ('Sindhudurg', 'Sindhudurg'), ('Solapur', 'Solapur'), ('Thane', 'Thane'), ('Wardha', 'Wardha'), ('Washim', 'Washim')], max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopeeapp.index'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='index',
            name='cat',
            field=models.IntegerField(choices=[(4, 'HP'), (2, 'Asus'), (5, 'Lenovo'), (3, 'Dell'), (1, 'Acer')], verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='index',
            name='offer',
            field=models.FloatField(verbose_name='Offer Discount'),
        ),
        migrations.AlterField(
            model_name='index',
            name='oprice',
            field=models.IntegerField(verbose_name='Offer Price'),
        ),
        migrations.AlterField(
            model_name='index',
            name='price',
            field=models.IntegerField(verbose_name='Original Price'),
        ),
        migrations.AlterField(
            model_name='index',
            name='rms',
            field=models.IntegerField(verbose_name='RAM Memory Installed Size'),
        ),
        migrations.AlterField(
            model_name='index',
            name='ss',
            field=models.FloatField(verbose_name='Screen Size'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopeeapp.index'),
        ),
        migrations.AlterField(
            model_name='order',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopeeapp.order'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopeeapp.index'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Userdb',
        ),
    ]
