# Generated by Django 4.2.4 on 2023-08-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopeeapp', '0003_alter_index_cat_alter_index_hds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='cat',
            field=models.IntegerField(choices=[(5, 'Lenovo'), (4, 'HP'), (3, 'Dell'), (1, 'Acer'), (2, 'Asus')], verbose_name='Category'),
        ),
    ]
