# Generated by Django 4.2.7 on 2023-11-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopeeapp', '0004_alter_index_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Acer'), (5, 'Lenovo'), (3, 'Dell'), (2, 'Asus'), (4, 'HP')], verbose_name='Category'),
        ),
    ]
